# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    versioning-strategy: increase
    groups:
      aws-cdk-dependencies:
        patterns:
          - "aws-cdk*"
          - "@aws-cdk/*"
      eslint-dependencies:
        patterns:
          - eslint
          - eslint-*
          - "@eslint/*"
          - "@eslint-community/*"
          - "@typescript-eslint/*"
      jest-dependencies:
        patterns:
          - jest
          - ts-jest
          - jest-*
          - "@jest/*"
